HomeWork3-Log_In
Alexei-Str/HomeWork pull request #2
Opened 2019-10-09 10:48 UTC by Alexei-Str

Были проблемы с заливом на гит, но вроде как в дедлайн уложился.
![Screenshot_1570610088](https://user-images.githubusercontent.com/14045147/66475102-5a75a280-ea9b-11e9-84fc-a16de6fb57e2.png)
![Screenshot_1570610113](https://user-images.githubusercontent.com/14045147/66475103-5b0e3900-ea9b-11e9-9d3d-92380457a2d2.png)

2019-10-10 21:36 UTC, NailShaykhrazievItis commented
30 коммитов эт сильно

2019-10-10 21:38 UTC, NailShaykhrazievItis requested changes

2019-10-10 21:38 UTC, NailShaykhrazievItis commented on hw3LogIn/app/src/main/java/com/example/hw3_login/Log_in.kt
> +class Log_in : AppCompatActivity() {
LogInActivity

2019-10-10 21:38 UTC, NailShaykhrazievItis commented on hw3LogIn/app/src/main/java/com/example/hw3_login/Pass_change.kt
> +class Pass_change : AppCompatActivity() {
PassChangeActivity

2019-10-10 21:38 UTC, NailShaykhrazievItis commented on hw3LogIn/app/src/main/res/layout/log_in.xml
> +        android:layout_width="121dp"
лучше не использовать абсолютыне значения. тут видтх = 0 и хеигхт = врап контент

2019-10-11 12:48 UTC, Alexei-Str commented
подправил

2019-10-11 19:17 UTC, NailShaykhrazievItis approved these changes

2019-10-11 19:57 UTC, closed without merging